### ISSUE TITLE
required intl 0.19.0 in Flutter 3.22.0

### ISSUE THREAD

**Issue by KamikazeZirou** [HoangNguyen0403/sheet_loader_localization#15]
Hi @HoangNguyenVMO

The dependency of sheet_loader_localization cannot be resolved in Flutter `3.22.0` which was released at 2024/5/14.
Flutter `3.22.0` pin the version intl to `0.19.0`. However sheet_loader_localization depends on `0.18.x`.

Can intl be updated from `^0.18.0` to `^0.19.0`?

**Comment by HoangNguyen0403** [comment]
Hi bro, thanks for highlight it. We'll have plan to delivery a new update version to support it on this week.
